version: '3'
services:
  kafka-manager:
    image: kafkamanager/kafka-manager:1.3.3.22
    ports:
    - 9000:9000
    environment:
    - ZK_HOSTS=host.docker.internal:2181
    - JAVA_OPTS=-Xmx256m -Xms256m
