version: '3'

services:
  connect:
    image: confluentinc/cp-kafka-connect
    environment:
    # required
    - CONNECT_BOOTSTRAP_SERVERS=host.docker.local:9092
    - CONNECT_GROUP_ID=quickstart
    - CONNECT_CONFIG_STORAGE_TOPIC=quickstart-config
    - CONNECT_OFFSET_STORAGE_TOPIC=quickstart-offsets
    - CONNECT_STATUS_STORAGE_TOPIC=quickstart-status
    - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
    - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
    - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
    - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
    - CONNECT_REST_ADVERTISED_HOST_NAME=host.docker.local
    - CONNECT_PLUGIN_PATH=/usr/share/java
    # optional
    - CONNECT_LOG4J_LOGGERS=org.reflections=ERROR
    # - CONNECT_REST_PORT=28082
