version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
    - 4369:4369
    - 5671-5672:5671-5672
    - 25672:25672
    - 15672:15672
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD-SHELL", "rabbitmqctl status"]
