version: '3'

services:
  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
    - 8081:8081
    environment:
    # required
    - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=host.docker.local:2181
    - SCHEMA_REGISTRY_HOST_NAME=host.docker.local
