version: '3'

services:
  schema-registry:
     image: confluentinc/cp-schema-registry
     container_name: schema-registry
     ports:
       - 8081:8081
     environment:
       # required
       - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=docker.for.mac.localhost:2181
       - SCHEMA_REGISTRY_HOST_NAME=docker.for.mac.localhost
