version: '3'

services:
  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
    - 8081:8081
    environment:
    # required
    - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=host.docker.internal:2181
    - SCHEMA_REGISTRY_HOST_NAME=host.docker.internal
    # enable cors to allow UI
    - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,OPTIONS
    - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN=*

  ui:
    image: landoop/schema-registry-ui
    ports:
    - 10080:8000
    environment:
    # use localhost for UI javacript to use schema-registry
    - SCHEMAREGISTRY_URL=http://localhost:8081
