version: '3'

volumes:
  data-db: {}

services:
  mongo:
    image: mongo:latest
    volumes:
    - data-db:/data/db
    # - .:/mnt
    command:
    - mongod
    - --storageEngine
    - wiredTiger
    ports:
    - 27017:27017
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo localhost:27017 --quiet"]
      interval: 5s
      timeout: 5s
      retries: 5
