version: '3'

volumes:
  data-db: {}

services:
  mongo:
    image: mongo:latest
    volumes:
      - data-db:/data/db
    command:
      - mongod
      - --storageEngine
      - wiredTiger
    ports:
      - "27017:27017"
