version: '3'

volumes:
  data: {}

services:
  mongo:
    image: mongo:4
    volumes:
    - data:/data/db
    # - .:/mnt
    command:
    - mongod
    ports:
    - 27017:27017
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo localhost:27017 --quiet"]
      interval: 5s
      timeout: 5s
      retries: 5
