version: '3'
services:
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "docker.for.mac.localhost:2181"
      JAVA_OPTS: '-Xmx256m -Xms256m'
