version: '3'

services:
  rest:
    image: confluentinc/cp-kafka-rest
    ports:
    - 8082:8082
    environment:
    # required
    - KAFKA_REST_HOST_NAME=host.docker.internal
    - KAFKA_REST_ZOOKEEPER_CONNECT=host.docker.internal:2181
    # - ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT=*
