version: '3'

services:
  rest:
    image: confluentinc/cp-kafka-rest
    ports:
      - 8082:8082
    environment:
      # required
      - KAFKA_REST_HOST_NAME=docker.for.mac.localhost
      - KAFKA_REST_ZOOKEEPER_CONNECT=docker.for.mac.localhost:2181
      # - ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT=*
