version: '3'

volumes:
  zk-1-data: {}
  zk-2-data: {}
  zk-3-data: {}
  kafka-1-data: {}
  kafka-2-data: {}
  kafka-3-data: {}

services:
  zk-1:
    image: confluentinc/cp-zookeeper:5.1.0
    ports:
    - 2181:2181
    environment:
    - ZOOKEEPER_SERVER_ID=1
    - ZOOKEEPER_SERVERS=zk-1:2888:3888;zk-2:2888:3888;zk-3:2888:3888
    # required
    - ZOOKEEPER_CLIENT_PORT=2181
    # optional
    - ZOOKEEPER_TICK_TIME=2000
    volumes:
    - zk-1-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181"]
      interval: 5s
      timeout: 10s
      retries: 5

  zk-2:
    image: confluentinc/cp-zookeeper:5.1.0
    ports:
    - 12181:2181
    environment:
    - ZOOKEEPER_SERVER_ID=2
    - ZOOKEEPER_SERVERS=zk-1:2888:3888;zk-2:2888:3888;zk-3:2888:3888
    # required
    - ZOOKEEPER_CLIENT_PORT=2181
    # optional
    - ZOOKEEPER_TICK_TIME=2000
    volumes:
    - zk-2-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181"]
      interval: 5s
      timeout: 10s
      retries: 5

  zk-3:
    image: confluentinc/cp-zookeeper:5.1.0
    ports:
    - 22181:2181
    environment:
    - ZOOKEEPER_SERVER_ID=3
    - ZOOKEEPER_SERVERS=zk-1:2888:3888;zk-2:2888:3888;zk-3:2888:3888
    # required
    - ZOOKEEPER_CLIENT_PORT=2181
    # optional
    - ZOOKEEPER_TICK_TIME=2000
    volumes:
    - zk-3-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181"]
      interval: 5s
      timeout: 10s
      retries: 5

  kafka-1:
    image: confluentinc/cp-kafka:5.1.0
    ports:
    - 9092:9092
    environment:
    # required
    - KAFKA_ZOOKEEPER_CONNECT=zk-1:2181,zk-2:2181,zk-3:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=INTERNAL_PLAINTEXT://kafka-1:9093,EXTERNAL_PLAINTEXT://localhost:9092
    - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_PLAINTEXT
    - KAFKA_LISTENERS=INTERNAL_PLAINTEXT://0.0.0.0:9093,EXTERNAL_PLAINTEXT://0.0.0.0:9092
    - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    # optional
    - KAFKA_BROKER_ID=1
    # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_NUM_PARTITIONS=3
    # - KAFKA_JMX_PORT=9999
    volumes:
    - kafka-1-data:/var/lib/kafka/data

  kafka-2:
    image: confluentinc/cp-kafka:5.1.0
    ports:
    - 19092:19092
    environment:
    # required
    - KAFKA_ZOOKEEPER_CONNECT=zk-1:2181,zk-2:2181,zk-3:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=INTERNAL_PLAINTEXT://kafka-2:9093,EXTERNAL_PLAINTEXT://localhost:19092
    - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_PLAINTEXT
    - KAFKA_LISTENERS=INTERNAL_PLAINTEXT://0.0.0.0:9093,EXTERNAL_PLAINTEXT://0.0.0.0:19092
    - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    # optional
    - KAFKA_BROKER_ID=2
    # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_NUM_PARTITIONS=3
    # - KAFKA_JMX_PORT=9999
    volumes:
    - kafka-2-data:/var/lib/kafka/data

  kafka-3:
    image: confluentinc/cp-kafka:5.1.0
    ports:
    - 29092:29092
    environment:
    # required
    - KAFKA_ZOOKEEPER_CONNECT=zk-1:2181,zk-2:2181,zk-3:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=INTERNAL_PLAINTEXT://kafka-3:9093,EXTERNAL_PLAINTEXT://localhost:29092
    - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_PLAINTEXT
    - KAFKA_LISTENERS=INTERNAL_PLAINTEXT://0.0.0.0:9093,EXTERNAL_PLAINTEXT://0.0.0.0:29092
    - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    # optional
    - KAFKA_BROKER_ID=3
    # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_NUM_PARTITIONS=3
    # - KAFKA_JMX_PORT=9999
    volumes:
    - kafka-3-data:/var/lib/kafka/data
