version: '3'

volumes:
  zk-1-data: {}
  zk-2-data: {}
  zk-3-data: {}
  kafka-1-data: {}
  kafka-2-data: {}
  kafka-3-data: {}

services:
  zk-1:
    image: confluentinc/cp-zookeeper
    ports:
    - 2181:2181
    environment:
    - ZOOKEEPER_SERVER_ID=1
    - ZOOKEEPER_SERVERS=zk-1:2888:3888;zk-2:2888:3888;zk-3:2888:3888
    # required
    - ZOOKEEPER_CLIENT_PORT=2181
    # optional
    - ZOOKEEPER_TICK_TIME=2000
    volumes:
    - zk-1-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181"]
      interval: 5s
      timeout: 10s
      retries: 5

  zk-2:
    image: confluentinc/cp-zookeeper
    ports:
    - 12181:2181
    environment:
    - ZOOKEEPER_SERVER_ID=2
    - ZOOKEEPER_SERVERS=zk-1:2888:3888;zk-2:2888:3888;zk-3:2888:3888
    # required
    - ZOOKEEPER_CLIENT_PORT=2181
    # optional
    - ZOOKEEPER_TICK_TIME=2000
    volumes:
    - zk-2-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181"]
      interval: 5s
      timeout: 10s
      retries: 5

  zk-3:
    image: confluentinc/cp-zookeeper
    ports:
    - 22181:2181
    environment:
    - ZOOKEEPER_SERVER_ID=3
    - ZOOKEEPER_SERVERS=zk-1:2888:3888;zk-2:2888:3888;zk-3:2888:3888
    # required
    - ZOOKEEPER_CLIENT_PORT=2181
    # optional
    - ZOOKEEPER_TICK_TIME=2000
    volumes:
    - zk-3-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181"]
      interval: 5s
      timeout: 10s
      retries: 5

  kafka-1:
    build: ./kafka-prometheus
    ports:
    - 9092:9092
    - 5556:5556
    environment:
    # required
    - KAFKA_ZOOKEEPER_CONNECT=zk-1:2181,zk-2:2181,zk-3:2181
    # KIP-103: Separation of Internal and External traffic
    # https://cwiki.apache.org/confluence/display/KAFKA/KIP-103%3A+Separation+of+Internal+and+External+traffic
    # Two gotcha to get external advertised listener working:
    # 1) use PLAINTEXT to mark external endpoint instead of EXTERNAL_PLAINTEXT
    # 2) put the external endpoint at front of the KAFKA_ADVERTISED_LISTENERS list
    # Reason: not all Kafka ecosystem fully supports KIP-103 yet
    # ex: https://github.com/confluentinc/schema-registry/issues/648
    # ex: https://github.com/yahoo/kafka-manager
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL_PLAINTEXT:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092,INTERNAL_PLAINTEXT://kafka-1:9093
    - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_PLAINTEXT
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,INTERNAL_PLAINTEXT://0.0.0.0:9093
    # optional
    - KAFKA_BROKER_ID=1
    - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_NUM_PARTITIONS=3
    # - KAFKA_JMX_PORT=9999
    - EXTRA_ARGS=-javaagent:/usr/local/share/jars/jmx_prometheus_javaagent-0.3.1.jar=5556:/opt/jmx_exporter/config.yml
    volumes:
    - kafka-1-data:/var/lib/kafka/data
    - ./jmx_exporter/config.yml:/opt/jmx_exporter/config.yml

  kafka-2:
    build: ./kafka-prometheus
    ports:
    - 19092:19092
    - 15556:5556
    environment:
    # required
    - KAFKA_ZOOKEEPER_CONNECT=zk-1:2181,zk-2:2181,zk-3:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL_PLAINTEXT:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:19092,INTERNAL_PLAINTEXT://kafka-2:9093
    - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_PLAINTEXT
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:19092,INTERNAL_PLAINTEXT://0.0.0.0:9093
    - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    # optional
    - KAFKA_BROKER_ID=2
    # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_NUM_PARTITIONS=3
    # - KAFKA_JMX_PORT=9999
    - EXTRA_ARGS=-javaagent:/usr/local/share/jars/jmx_prometheus_javaagent-0.3.1.jar=5556:/opt/jmx_exporter/config.yml
    volumes:
    - kafka-2-data:/var/lib/kafka/data
    - ./jmx_exporter/config.yml:/opt/jmx_exporter/config.yml

  kafka-3:
    build: ./kafka-prometheus
    ports:
    - 29092:29092
    - 25556:5556
    environment:
    # required
    - KAFKA_ZOOKEEPER_CONNECT=zk-1:2181,zk-2:2181,zk-3:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL_PLAINTEXT:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:29092,INTERNAL_PLAINTEXT://kafka-3:9093
    - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_PLAINTEXT
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,INTERNAL_PLAINTEXT://0.0.0.0:9093
    - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    # optional
    - KAFKA_BROKER_ID=3
    # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_NUM_PARTITIONS=3
    # - KAFKA_JMX_PORT=9999
    - EXTRA_ARGS=-javaagent:/usr/local/share/jars/jmx_prometheus_javaagent-0.3.1.jar=5556:/opt/jmx_exporter/config.yml
    volumes:
    - kafka-3-data:/var/lib/kafka/data
    - ./jmx_exporter/config.yml:/opt/jmx_exporter/config.yml
