version: '3'

volumes:
  data: {}

services:
  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # - MYSQL_USER=test
    # - MYSQL_PASSWORD=test
    volumes:
    - data:/var/lib/mysql
