version: '3'

services:
  kong:
    image: kong:0.12.3
    environment:
      - KONG_PG_HOST=database
      - KONG_DATABASE=postgres
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    # command: kong migrations up
    depends_on:
      - database

  database:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  dashboard:
    image: pgbi/kong-dashboard:v3
    ports:
      - 8080:8080
    entrypoint: ./docker/entrypoint_dev.sh
    # command: bin/kong-dashboard.js start --kong-url http://kong:8001
