version: '3'

volumes:
  es-data-0: {}

services:
  es-0:
    build: ../elasticsearch
    image: elasticsearch-local
    ports:
    - 9200:9200
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
    - node.name=es-0
    - node.master=true
    - cluster.name=es.cluster.local
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
    - es-data-0:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 30s
      retries: 5

  kibana:
    build: ../kibana
    image: kibana-local
    ports:
    - 5601:5601
    environment:
    - ELASTICSEARCH_URL=http://es-0:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:5601"]
      interval: 15s
      timeout: 30s
      retries: 10

  # jupyter service to learn ES for Spark
  # jupyter:
  #   image: jupyter/all-spark-notebook:latest
  #   ports:
  #     - "8888:8888"
  #     - "4040:4040"
  #   volumes:
  #     - /Users:/Users
  #     - /Users/ziruzhu/Dropbox/dev/notebooks:/home/jovyan/notebooks
