version: '3.3'

volumes:
  es-data-0:
    driver: local

services:
  es-0:
    build: ../elasticsearch
    image: elasticsearch-local
    ports:
      - "9200:9200"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - node.name=es-0
      - node.master=true
      - cluster.name=es.cluster.local
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - es-data-0:/usr/share/elasticsearch/data

  kibana:
    build: ../kibana
    image: kibana-local
    ports:
      - "5601:5601"
    links:
      - es-0:elasticsearch

  # jupyter service to learn ES for Spark
  # jupyter:
  #   image: jupyter/all-spark-notebook:latest
  #   ports:
  #     - "8888:8888"
  #     - "4040:4040"
  #   volumes:
  #     - /Users:/Users
  #     - /Users/ziruzhu/Dropbox/dev/notebooks:/home/jovyan/notebooks
