version: '3'

services:
  topics-ui:
    image: landoop/kafka-topics-ui
    ports:
    - 8000:8000
    environment:
    - KAFKA_REST_PROXY_URL=http://rest:8082
    - PROXY=true

  rest:
    image: confluentinc/cp-kafka-rest
    ports:
    - 8082:8082
    environment:
    # required
    - KAFKA_REST_HOST_NAME=host.docker.internal
    - KAFKA_REST_ZOOKEEPER_CONNECT=host.docker.internal:2181
    # - ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT=*
