version: '3'

services:
  topics-ui:
    image: landoop/kafka-topics-ui
    ports:
      - 8000:8000
    environment:
      - KAFKA_REST_PROXY_URL=http://docker.for.mac.localhost:8082
      - PROXY=true
