version: '3'

volumes:
  zk-data: {}
  kafka-data: {}

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
    - 2181:2181
    environment:
    # required
    - ZOOKEEPER_CLIENT_PORT=2181
    # optional
    - ZOOKEEPER_TICK_TIME=2000
    volumes:
    - zk-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181"]
      interval: 5s
      timeout: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka
    ports:
    - 9092:9092
    - 9093:9093
    # - 9999:9999
    environment:
    # required
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL_LISTENER:PLAINTEXT,DOCKER_LISTENER:PLAINTEXT,INTER_LISTENER:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=EXTERNAL_LISTENER://localhost:9092,DOCKER_LISTENER://host.docker.internal:9093,INTER_LISTENER://kafka:9094
    - KAFKA_LISTENERS=EXTERNAL_LISTENER://0.0.0.0:9092,DOCKER_LISTENER://0.0.0.0:9093,INTER_LISTENER://0.0.0.0:9094
    - KAFKA_INTER_BROKER_LISTENER_NAME=INTER_LISTENER
    # optional
    - KAFKA_BROKER_ID=1
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    # - KAFKA_JMX_PORT=9999
    volumes:
    - kafka-data:/var/lib/kafka/data
    depends_on:
    - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --zookeeper zookeeper:2181 --list"]
      interval: 5s
      timeout: 10s
      retries: 5
