version: '3.2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
        - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      # - KAFKA_ADVERTISED_HOST_NAME=docker.for.mac.localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://docker.for.mac.localhost:9092
    depends_on:
      - zookeeper
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
