version: '3'

services:
  web:
    image: elkozmon/zoonavigator-web:latest
    ports:
    - 28000:8000
    environment:
    - API_HOST=api
    - API_PORT=9000
    depends_on:
    - api

  api:
    image: elkozmon/zoonavigator-api:latest
    environment:
    - SERVER_HTTP_PORT=9000
