version: '3'

volumes:
  data: {}

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data
      - .:/data
