version: '3'

volumes:
  data: {}

services:
  redis:
    image: redis:alpine
    ports:
    - 6379:6379
    volumes:
    - data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 3s
      retries: 10
