version: '2'

volumes:
  data: {}

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - data:/data

  redis-cli:
    image: redis:alpine
    links:
      - redis:redis
    command:
      - redis-cli
      - -h
      - redis
      - -p
      - '6379'
